services:
# dodaj usługę helloworld
  helloworld:
     container_name: helloworld # nazwa kontenera
     image: crccheck/hello-world # skorzystaj z obrazu

# dodaj usługę nginx
  nginx:
     container_name: nginx
     restart: unless-stopped # kontener będzie resetowany chyba że jest zatrzymany ręcznie
     image: nginx 
     ports:
      - 80:80
      - 443:443
     volumes: # określ wolumeny – pliki konfiguracyjne
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # pobierz plik konfiguracyjny z lokalnego folderu nginx
      - ./certbot/conf:/etc/letsencrypt # wymóg certbota
      - ./certbot/www:/var/www/certbot # wymóg certbota
      - ./nginx/index.html:/var/www/html/index.html # pobierz plik strony internetowej

# dodaj usługę certbot
  certbot:
     image: certbot/certbot
     container_name: certbot
     volumes:
      - ./certbot/conf:/etc/letsencrypt # wymóg certbota
      - ./certbot/www:/var/www/certbot # wymóg certbota
     # wykonaj polecenie certyfikujące
     # --webroot – umieść plik weryfikacyjny w katalogu domeny (-w wskazuje katalog)
     # --force-renewal – zmusza usługę certbot do odnowienia certyfikatu
     # --email – flaga określająca adres e-mail używany do powiadomień
     # -d – określa nazwę domeny, dla której żądany jest certyfikat SSL
     # --agree-tos – zgoda na warunki korzystania z usługi Let's Encrypt
     command: certonly --webroot -w /var/www/certbot --force-renewal --email s97703@pollub.edu.pl -d dockerlab3.website --agree-tos